### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dawangandypeng** [ibmdbanalytics/ibmdbpy#29]
import os
import sys
from ibmdbpy import IdaDataBase

classpath=os.environ['CLASSPATH'] = "./db2jcc4.jar;"
print ('CLASSPATH: ', os.environ['CLASSPATH'])

#Enter the values for you database connection, please replace them with actual values
dsn_database = "BLUDB"
dsn_hostname = "dashdb-entry-yp-dal09-09.services.dal.bluemix.net"
dsn_port = "50000"
dsn_uid = "dash100907"
dsn_pwd = "sbCrE0M0KeCX"
connection_string='jdbc:db2://'+dsn_hostname+':'+dsn_port+'/'+dsn_database+':user='+dsn_uid+';password='+dsn_pwd+";"

print(connection_string)
# connect to DB

idadb=IdaDataBase(dsn=connection_string)

# print if table is existing in DB. TRUE stands for table existing.
print (idadb.exists_table("dash100907.cms"))

I am running this script on Windows 7 and Python version 3.6.4.
Getting the following error.

Traceback (most recent call last):
  File "xxxxxxx/scripts/testing.py", line 20, in <module>
    idadb=IdaDataBase(dsn=connection_string)
  File "C:\Python36-32\lib\site-packages\ibmdbpy\base.py", line 245, in __init__
    jarpath = jarpath.split(':')[1].replace('\\', '/') # get rid of windows style formatting
IndexError: list index out of range

By the way, it's working on MAC actually.  It doesn't work on both Window 7 and 10.

**Comment by dawangandypeng** [comment]
Actually, I tried different format and did not work

os.environ['CLASSPATH'] = ".\\db2jcc4.jar"
os.environ['CLASSPATH'] = "absolute path\\db2jcc4.jar"
